[package]
name = "simple-disk-benchmark"
version = "0.1.1"
edition = "2021"
description = "A simple disk benchmark tool"

authors = ["Jonathan Wight"]
categories = ["command-line-utilities", "filesystem"]
homepage = "https://github.com/schwa/simple-disk-benchmark-rs"
keywords = ["benchmark", "cli", "disk"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/schwa/simple-disk-benchmark-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
bytesize = "1.2.0"
clap = { version = "4.3.19", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
colored = "2.0.4"
console = "0.15.7"
derive-enum-from-into = "0.1.1"
enum-display-derive = "0.1.1"
indicatif = "0.17.5"
lazy_static = "1.4.0"
libc = "0.2.147"
log = "0.4.19"
minijinja = "1.0.5"
nom = "7.1.3"
rand = "0.8.5"
regex = "1.9.1"
simple_logger = { version = "4.2.0", features = ["stderr"] }
statistical = "1.0.0"
