[package]
name = "simple-disk-benchmark"
edition = "2021"
version = "0.1.3"
authors = ["Jonathan Wight"]
description = "A simple disk benchmark tool"
homepage = "https://github.com/schwa/simple-disk-benchmark-rs"
readme = "README.md"
keywords = ["benchmark", "cli", "disk"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"
repository = "https://github.com/schwa/simple-disk-benchmark-rs"

[dependencies]
anyhow = "1.0.72"
clap-verbosity-flag = "2.0.1"
colored = "2.0.4"
enum-display-derive = "0.1.1"
humantime = "2.1.0"
indicatif = "0.17.5"
lazy_static = "1.4.0"
libc = "0.2.147"
nom = "7.1.3"
num-traits = "0.2.16"
os_info = "3.7.0"
rand = "0.8.5"
rasciigraph = "0.2.0"
regex = "1.9.1"
serde_json = "1.0.104"
statistical = "1.0.0"

[dependencies.clap]
version = "4.3.19"
features = ["derive"]
optional = false

[dependencies.fern]
version = "0.6.2"
features = ["colored"]
optional = false

[dependencies.log]
version = "0.4.19"
features = []
optional = false

[dependencies.minijinja]
version = "1.0.5"
features = ["multi_template", "deserialization"]
optional = false
default-features = false

[dependencies.serde]
version = "1.0.180"
features = ["derive"]
optional = false

[dependencies.strum]
version = "0.25.0"
features = ["derive"]
optional = false

[dependencies.time]
version = "0.3.24"
features = ["serde-human-readable", "local-offset"]
optional = false
