[package]
name = "simple-disk-benchmark"
version = "0.1.3"
edition = "2021"
description = "A simple disk benchmark tool"

authors = ["Jonathan Wight"]
categories = ["command-line-utilities", "filesystem"]
homepage = "https://github.com/schwa/simple-disk-benchmark-rs"
keywords = ["benchmark", "cli", "disk"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/schwa/simple-disk-benchmark-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [profile.release]
# strip = true
# lto = true
# codegen-units = 1
# panic = "abort"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
colored = "2.0.4"
console = "0.15.7"
enum-display-derive = "0.1.1"
fern = { version = "0.6.2", features = ["colored"] }
humantime = "2.1.0"
indicatif = "0.17.5"
lazy_static = "1.4.0"
libc = "0.2.147"
log = { version = "0.4.19" }
minijinja = "1.0.5"
nom = "7.1.3"
num-traits = "0.2.16"
os_info = "3.7.0"
rand = "0.8.5"
rasciigraph = "0.2.0"
regex = "1.9.1"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
statistical = "1.0.0"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3.24", features = [
    "serde-human-readable",
    "local-offset",
] }
